rules = [["Suffix", "fb.com", "ğŸ”°å›½å¤–æµé‡"], ["Keyword", "facebook", "ğŸ”°å›½å¤–æµé‡"]]

[[services]]
name = "ss"
type = "vmess"
server = "ss.dsds"
port = 1131
uuid = "323232323"
cipher = "aes123gcm"
